name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint E:\LintTemplates\bad-template.yaml > lint-results.txt

      - name: Convert cfn-lint results
        run: |
          python parse_cfn_lint_results.py lint-results.txt cfn-lint-results.json

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Final2 \
            -Dsonar.organization=Bali \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.issueReportPaths=cfn-lint-results.json

